init:
  services:
    mysql: {}

  script: |
    echo DB_USER: $DB_USER
    env 

  variables:
    DB_USER: sparky
    DB_PASS: sparky123
    DB_NAME: sparky_test111

main:
  with-code-coverage: false
